### ISSUE TITLE
What feast versions are currently supported?

### ISSUE THREAD

**Issue by Felix-neko** [baineng/feast-hive#6] opened 2021-10-26 08:22 UTC
Hi!

Can you tell me, what versions of `feast` are currently supported?

**Comment by baineng** [comment] 2021-11-01 01:28
@Felix-neko , it's Feast 0.12.0 when I was developing, I will check if newer version working as well.

@itsmesrds There is no limitation, external tables should work I think.

**Comment by Felix-neko** [comment] 2021-11-01 09:20
> @Felix-neko , it's Feast 0.12.0 when I was developing, I will check if newer version working as well.

I've made some changes to support 0.14 version in my fork. Here's my PR: https://github.com/baineng/feast-hive/pull/8

Maybe it will be helpful = )

**Comment by baineng** [comment] 2021-11-04 12:19
@Felix-neko @itsmesrds FYI,  I've already merged the PR into main.
But I want make some improvements and tests before release a new version.

@Felix-neko Could you tell me what's the user case of "final_feature_names", how do I reproduce that? thanks!

**Comment by Felix-neko** [comment] 2021-11-05 10:17
> FYI, I've already merged the PR into main.

Great! I was glad to help you ^_^

> @Felix-neko Could you tell me what's the user case of "final_feature_names", how do I reproduce that? thanks!

I've added this argument to have the possibility to externally set feature names (if Hive is working in `unique.field.names=true` mode it gives field names like `table_name.field_name` instead of just `field_name` and in this case feature names extracted from resulting cursor description didn't correspond with the ordered). Just now I'm using `unique.field.names=false` and this argument isn't actually needed, but I'm afraid that `feast-hive` can start to fail if we have duplicating field names in different tables (e.g. if we select features like ["house:age", "buyer:age"])

P.S. I think that for better testing we need some more complex database with 2-3 tables that have fields with same names. If you need one, I can provide it in a couple of days.

**Comment by baineng** [comment] 2021-11-05 22:48
> @baineng
> 
> > FYI, I've already merged the PR into main.
> 
> Great! I was glad to help you ^_^
> 
> > @Felix-neko Could you tell me what's the user case of "final_feature_names", how do I reproduce that? thanks!
> 
> I've added this argument to have the possibility to externally set feature names (if Hive is working in `unique.field.names=true` mode it gives field names like `table_name.field_name` instead of just `field_name` and in this case feature names extracted from resulting cursor description didn't correspond with the names we want). Just now I'm using `unique.field.names=false` and this argument isn't actually needed, but I'm afraid that `feast-hive` can start to fail if we have duplicating field names in different tables (e.g. if we select features like `["house:age", "buyer:age"]`)
> 
> P.S. I think that for better testing we need some more complex database with 2-3 tables that have fields with same names. If you need one, I can provide it in a couple of days.

Great! that sounds like an issue, I will try to cover it, thanks again for your contribution.

**Comment by baineng** [comment] 2021-11-06 16:00
Hello @Felix-neko, I've made some changes in main branch, include:
- Removed the final_feature_names, I think it's possibly not needed, since I forced `unique.field.names=true` in all queries and if there were duplicated fields, people can use full_feature_name
- Reverted some test code, you can have you local test version if it's convenient for you.

Please let me know if you had any concerns or thoughts, also it will be appreciated if you had the test case for `complex tables`.

**Closed** 2021-11-11 04:49 UTC
Labels: bug

**Comment by itsmesrds** [comment] 2021-11-11 05:05
@baineng  I know, it might be miscellaneous to this issue, but just wanted to know. Is any optimization done in hive-feast which is native to hive ?  like partitioning, bucketing? 

Even while ingesting the data to the hive, if we wanted partition on event_timestamp column or entity column or on both. will the query performance is better ?

**Comment by baineng** [comment] 2021-11-11 05:55
@itsmesrds That's a good question, I have done any performance optimization yet, since the query is quite complex and for now mostly is making it work. 
Performance optimization will be considered later or any help is welcome.
